Updated to work on Fedora21
Without thihs change, make fails at...

[ 34%] Building CXX object libgrive/CMakeFiles/grive.dir/src/protocol/Json.cc.o
/home/shawn.lopresto/repos/grive/libgrive/src/protocol/Json.cc:32:31: fatal error: json/json_tokener.h: No such file or directory
 #include <json/json_tokener.h>